Repository raisiqueira/use-viacep, pull requests merged in 2023-01, with the labels that each got.

#227 chore: update deps
  package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#228 bug: remove vitest de dependencias de produção e corrige script de coverage
  lib/package.json
  package.json
Labels: enhancement, good first issue

#229 chore: project improvements
  .gitignore
  lib/mock/server.ts
  lib/package.json
  lib/src/index.ts
  lib/vitestSetup.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement
